# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        # brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf pkg-config
        # brew install Caskroom/cask/xquartz
        # brew install portmidi
        # python3 -m pip install git+https://github.com/pygame/pygame.git
        # python3 -m pygame.tests
        
        python -m pip install --upgrade pip
        pip install opencv-python mediapipe numpy pygame
    - name: Create Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.6'
        spec: 'TrickOrTreatPy.py'
        # requirements: 'src/requirements.txt'
        upload_exe_with_name: 'My executable'
        options: --onefile, --name "My App", --windowed, 
